package ai.qorva.core.dto;

public enum InsightIntent {
    TALENT_POOL_INTELLIGENCE,
    SKILL_GAP_ANALYSIS,
    CANDIDATE_RANKING,
    CANDIDATE_REDISCOVERY,
    TALENT_CLUSTERING,
    GENERAL_RECRUITING_QUESTION
}
