package ai.qorva.core.dto;

public enum InsightIntent {
    TALENT_POOL_INTELLIGENCE,
    SKILL_GAP_ANALYSIS,
    CANDIDATE_RANKING,
    CANDIDATE_REDISCOVERY,
    TALENT_CLUSTERING,
    GENERAL_RECRUITING_QUESTION,
    // Phase 2 — declared but no handler wired yet; routes to GENERAL_RECRUITING_QUESTION
    LOCATION_INTELLIGENCE,
    SALARY_EXPECTATION_ANALYSIS,
    CANDIDATE_COMPARISON,
    JOB_DESCRIPTION_ANALYSIS,
    RESUME_DATA_QUALITY_ANALYSIS,
    SENIORITY_DISTRIBUTION_ANALYSIS
}
