server:
  servlet:
    context-path: /


management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    mail:
      enabled: false


spring:
  application:
    name: qorva-ai