server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    mail:
      enabled: true


spring:
  application:
    name: qorva-ai