server:
  servlet:
    context-path: /


management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    mail:
      enabled: false


spring:
  application:
    name: qorva-ai
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 500MB
  messages:
    basename: messages/errors
    encoding: UTF-8
    use-code-as-default-message: true
  ai:
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 1s
        multiplier: 2
        max-interval: 10s
      on-client-errors: false

mongock:
  migration-scan-package: ai.qorva.core.migrations

qorva:
  products:
    starter:
      stripe-product-name: Starter
      features:
        seats: 2
        limits:
          screening-actions: 1000
          ai-resume-chats: 300
          talent-intelligence-queries: 500
        overage:
          enabled: false
          screening-action-price: 0.0
          chat-price: 0.0
          intelligence-query-price: 0.0
    pro:
      stripe-product-name: Pro
      features:
        seats: 5
        limits:
          screening-actions: 5000
          ai-resume-chats: 700
          talent-intelligence-queries: 1500
        overage:
          enabled: true
          screening-action-price: 0.02
          chat-price: 0.10
          intelligence-query-price: 0.50
    scale:
      stripe-product-name: Scale
      features:
        seats: 10
        limits:
          screening-actions: 12000
          ai-resume-chats: 2000
          talent-intelligence-queries: 4000
        overage:
          enabled: true
          screening-action-price: 0.02
          chat-price: 0.10
          intelligence-query-price: 0.50


