package ai.qorva.core.enums;

import lombok.Getter;

@Getter
public enum SubscriptionStatus {
    FREE_TRIAL_PERIOD_ACTIVE("FREE_TRIAL_PERIOD_ACTIVE"),
    FREE_TRIAL_PERIOD_FINISHED("FREE_TRIAL_PERIOD_FINISHED"),
    SUBSCRIPTION_ACTIVE("SUBSCRIPTION_ACTIVE"),
    SUBSCRIPTION_EXPIRED("SUBSCRIPTION_EXPIRED"),
    SUBSCRIPTION_LOCKED("SUBSCRIPTION_LOCKED"),
    CANCELLATION_GRACE_PERIOD_ACTIVE("CANCELLATION_GRACE_PERIOD_ACTIVE"),
    CANCELLATION_GRACE_PERIOD_FINISHED("CANCELLATION_GRACE_PERIOD_FINISHED");

    SubscriptionStatus(String value) {
        this.value = value;
    }
    private final String value;
}
