package ai.qorva.core.enums;

import lombok.Getter;

@Getter
public enum SubscriptionStatus {
    FREE_TRIAL_PERIOD_ACTIVE("FREE_TRIAL_PERIOD_ACTIVE"),
    SUBSCRIPTION_PAYMENT_FAILED("SUBSCRIPTION_PAYMENT_FAILED"),
    SUBSCRIPTION_ACTIVE("SUBSCRIPTION_ACTIVE"),
    SUBSCRIPTION_EXPIRED("SUBSCRIPTION_EXPIRED"),
    SUBSCRIPTION_LOCKED("SUBSCRIPTION_LOCKED"),
    SUBSCRIPTION_INCOMPLETE("SUBSCRIPTION_INCOMPLETE"),
    SUBSCRIPTION_FAILED("SUBSCRIPTION_FAILED"),
    SUBSCRIPTION_CANCELLED("SUBSCRIPTION_CANCELLED"),
    CANCELLATION_GRACE_PERIOD_STARTED("CANCELLATION_GRACE_PERIOD_STARTED"),
    CANCELLATION_GRACE_PERIOD_FINISHED("CANCELLATION_GRACE_PERIOD_FINISHED");

    SubscriptionStatus(String value) {
        this.value = value;
    }
    private final String value;
}
