package ai.qorva.core.enums;

import lombok.Getter;

@Getter
public enum UserActionsEnum {
	// Dashboard
	VIEW_DASHBOARD("VIEW_DASHBOARD"),

	// CV
	ADD_CV("ADD_CV"),
	VIEW_CV("VIEW_CV"),
	MODIFY_CV("MODIFY_CV"),
	DELETE_CV("DELETE_CV"),

	// Jobs
	ADD_JOB("ADD_JOB"),
	VIEW_JOB("VIEW_JOB"),
	MODIFY_JOB("MODIFY_JOB"),
	DELETE_JOB("DELETE_JOB"),

	// Reports
	GENERATE_REPORT("GENERATE_REPORT"),
	VIEW_REPORT("VIEW_REPORT"),
	MODIFY_REPORT("MODIFY_REPORT"),
	DELETE_REPORT("DELETE_REPORT"),

	// Chat
	START_CHAT("START_CHAT"),
	VIEW_CHAT("VIEW_CHAT"),
	VIEW_MESSAGE("VIEW_MESSAGE"),
	REPLY_MESSAGE("REPLY_MESSAGE"),
	MODIFY_CHAT("MODIFY_CHAT"),
	DELETE_CHAT("DELETE_CHAT"),

	// ATS Export Reports
	ATS_REPORT_EXPORT("ATS_REPORT_EXPORT"),

	// Billing
	UPDATE_SUBSCRIPTION("UPDATE_SUBSCRIPTION"),
	CANCEL_SUBSCRIPTION("CANCEL_SUBSCRIPTION");

	UserActionsEnum(String value) {
		this.value = value;
	}
	private final String value;
}
