package ai.qorva.core.service.ats.connectors;

import ai.qorva.core.enums.AtsProviderEnum;
import ai.qorva.core.exception.QorvaException;
import ai.qorva.core.service.ats.AtsConnector;
import ai.qorva.core.service.ats.AtsCredentials;
import ai.qorva.core.service.ats.AtsHttpClient;
import ai.qorva.core.service.ats.AtsModels.AtsCandidate;
import ai.qorva.core.service.ats.AtsModels.AtsFile;
import ai.qorva.core.service.ats.AtsModels.AtsJob;
import ai.qorva.core.service.ats.AtsModels.AtsPage;
import ai.qorva.core.service.ats.AtsModels.AtsWebhookEvent;
import ai.qorva.core.service.ats.AtsModels.MatchWriteBack;
import ai.qorva.core.service.ats.AtsWebhookVerifier;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * Ashby API. Every endpoint is a POST RPC (candidate.list, job.list, file.info) rather
 * than a REST GET, authenticated with HTTP Basic where the API key is the username and
 * the password is empty — the key is generated by the customer in their own Ashby admin,
 * so no partner approval stands between a tenant and a working connection.
 *
 * <p>Paging is an opaque cursor Ashby hands back, replayed verbatim like Workable's next
 * links. Resumes are two-step: the candidate carries a file handle, and file.info trades
 * it for a short-lived download URL. Webhooks are signed (Ashby-Signature, HMAC-SHA256).</p>
 */
@Slf4j
@Component
public class AshbyConnector implements AtsConnector {

	private static final String BASE = "https://api.ashbyhq.com";
	private static final int PAGE_SIZE = 100;

	/** Marks a mid-run continuation so it is never confused with a durable ISO timestamp. */
	private static final String CURSOR_PREFIX = "ashby:";

	private final AtsHttpClient http;
	private final ObjectMapper objectMapper;

	public AshbyConnector(AtsHttpClient http, ObjectMapper objectMapper) {
		this.http = http;
		this.objectMapper = objectMapper;
	}

	@Override
	public AtsProviderEnum provider() {
		return AtsProviderEnum.ASHBY;
	}

	private Map<String, String> auth(AtsCredentials credentials) {
		var token = Base64.getEncoder()
			.encodeToString((credentials.getApiKey() + ":").getBytes(StandardCharsets.UTF_8));
		return Map.of("Authorization", "Basic " + token);
	}

	@Override
	public void validate(AtsCredentials credentials) throws QorvaException {
		http.postJson(provider(), BASE + "/candidate.list", auth(credentials), Map.of("limit", 1));
	}

	@Override
	public AtsPage<AtsJob> listJobs(AtsCredentials credentials, String cursor) throws QorvaException {
		var body = http.postJson(provider(), BASE + "/job.list", auth(credentials), pageRequest(cursor));
		var jobs = new ArrayList<AtsJob>();
		for (JsonNode node : body.path("results")) {
			var status = node.path("status").asText("");
			jobs.add(new AtsJob(
				node.path("id").asText(),
				node.path("title").asText(null),
				// Ashby keeps prose on the job posting, not the job; the team name is the
				// only description-shaped text on this payload.
				node.path("departmentName").asText(node.path("teamName").asText(null)),
				"Open".equalsIgnoreCase(status),
				parseTime(node.path("updatedAt").asText(null)),
				node.path("jobUrl").asText(null)));
		}
		return new AtsPage<>(jobs, nextCursor(body));
	}

	@Override
	public AtsPage<AtsCandidate> listCandidates(AtsCredentials credentials, String cursor) throws QorvaException {
		var body = http.postJson(provider(), BASE + "/candidate.list", auth(credentials), pageRequest(cursor));
		var candidates = new ArrayList<AtsCandidate>();
		for (JsonNode node : body.path("results")) {
			candidates.add(new AtsCandidate(
				node.path("id").asText(),
				firstApplicationId(node),
				node.path("name").asText(null),
				primaryEmail(node),
				parseTime(node.path("updatedAt").asText(null)),
				node.path("profileUrl").asText(null),
				resumeHandle(node),
				resumeFilename(node)));
		}
		return new AtsPage<>(candidates, nextCursor(body));
	}

	/**
	 * A durable cursor (an ISO timestamp from the last completed run) starts a fresh listing:
	 * Ashby filters deltas by sync token rather than timestamp, and the engine already skips
	 * unchanged candidates on updatedAt before spending anything on them.
	 */
	private Map<String, Object> pageRequest(String cursor) {
		var request = new HashMap<String, Object>();
		request.put("limit", PAGE_SIZE);
		if (cursor != null && cursor.startsWith(CURSOR_PREFIX)) {
			request.put("cursor", cursor.substring(CURSOR_PREFIX.length()));
		}
		return request;
	}

	private String nextCursor(JsonNode body) {
		if (!body.path("moreDataAvailable").asBoolean(false)) {
			return null;
		}
		var next = body.path("nextCursor").asText(null);
		return next == null ? null : CURSOR_PREFIX + next;
	}

	private String primaryEmail(JsonNode candidate) {
		var primary = candidate.path("primaryEmailAddress").path("value").asText(null);
		if (primary != null) {
			return primary;
		}
		for (JsonNode address : candidate.path("emailAddresses")) {
			var value = address.path("value").asText(null);
			if (value != null) {
				return value;
			}
		}
		return null;
	}

	private String firstApplicationId(JsonNode candidate) {
		var applications = candidate.path("applicationIds");
		return applications.isArray() && !applications.isEmpty() ? applications.get(0).asText() : null;
	}

	private JsonNode resumeNode(JsonNode candidate) {
		var direct = candidate.path("resumeFileHandle");
		if (!direct.isMissingNode() && direct.path("handle").asText(null) != null) {
			return direct;
		}
		for (JsonNode file : candidate.path("fileHandles")) {
			if (file.path("name").asText("").toLowerCase().contains("resume")
				|| "Resume".equalsIgnoreCase(file.path("type").asText(""))) {
				return file;
			}
		}
		return null;
	}

	private String resumeHandle(JsonNode candidate) {
		var node = resumeNode(candidate);
		return node == null ? null : node.path("handle").asText(null);
	}

	private String resumeFilename(JsonNode candidate) {
		var node = resumeNode(candidate);
		return node == null ? null : node.path("name").asText(null);
	}

	@Override
	public AtsFile downloadResume(AtsCredentials credentials, AtsCandidate candidate) throws QorvaException {
		if (candidate.resumeHandle() == null) {
			return null;
		}
		// file.info trades the handle for a signed, short-lived URL on Ashby's storage host.
		var info = http.postJson(provider(), BASE + "/file.info", auth(credentials),
			Map.of("fileHandle", candidate.resumeHandle()));
		var url = info.path("results").path("url").asText(null);
		if (url == null) {
			return null;
		}
		var bytes = http.getBytes(provider(), url, Map.of());
		if (bytes == null || bytes.length == 0) {
			return null;
		}
		return new AtsFile(bytes,
			candidate.resumeFilename() != null ? candidate.resumeFilename() : "resume.pdf", null);
	}

	@Override
	public void pushMatchResult(AtsCredentials credentials, MatchWriteBack payload) throws QorvaException {
		http.postJson(provider(), BASE + "/candidate.createNote", auth(credentials), Map.of(
			"candidateId", payload.externalCandidateId(),
			"note", NoteFormat.text(payload),
			"sendNotifications", false));
	}

	@Override
	public Optional<AtsWebhookEvent> parseWebhook(HttpHeaders headers, byte[] body, String webhookSecret) {
		var signature = headers.getFirst("Ashby-Signature");
		if (signature == null) {
			return Optional.empty();
		}
		var provided = signature.replace("sha256=", "").trim();
		if (!AtsWebhookVerifier.matches(AtsWebhookVerifier.hmacHex(body, webhookSecret), provided)) {
			return Optional.empty();
		}
		try {
			var json = objectMapper.readTree(body);
			var data = json.path("data");
			var candidateId = data.path("candidate").path("id").asText(
				data.path("application").path("candidate").path("id").asText(null));
			return Optional.of(new AtsWebhookEvent(json.path("action").asText("event"), candidateId));
		} catch (Exception e) {
			return Optional.empty();
		}
	}

	private static Instant parseTime(String iso) {
		try {
			return iso == null ? null : Instant.parse(iso);
		} catch (Exception e) {
			return null;
		}
	}
}
