package ai.qorva.core.service.ats;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;

/**
 * Decrypted provider credentials. Lives only in memory during a request or sync run —
 * persisted exclusively as the encrypted blob on AtsConnection. Which fields are used
 * depends on the provider: apiKey for token providers, clientId/clientSecret for
 * Greenhouse Harvest v3, the OAuth trio for Zoho/Lever, subdomain/companyId as path
 * segments, onBehalfOfUserId for Greenhouse notes.
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AtsCredentials {

	private String apiKey;

	/**
	 * Greenhouse Harvest v3 credentials, generated by the customer in their own Dev Center
	 * ("Unlisted vendor") and exchanged for a short-lived bearer token via the OAuth
	 * client-credentials grant. No partner approval and no user redirect are involved, so
	 * these arrive through the ordinary connect form rather than the OAuth callback.
	 */
	private String clientId;
	private String clientSecret;

	/** BambooHR / Workable subdomain, Recruitee company id — path segments only. */
	private String subdomain;
	private String companyId;

	/**
	 * Greenhouse user id the integration acts as. Sent as the client-credentials `sub`
	 * parameter on v3, and as the On-Behalf-Of header that Harvest requires for note writes.
	 */
	private String onBehalfOfUserId;

	private String accessToken;
	private String refreshToken;
	private Instant tokenExpiresAt;

	/**
	 * HMAC key for inbound webhooks when the provider picks it rather than accepting the
	 * connection's own webhookSecret. Lever generates a signing token per account; it lives
	 * here, inside the encrypted blob, because it is a secret like any other credential.
	 */
	private String webhookSigningSecret;

	/** Workable account id, discovered at registration — its subscriptions API requires it. */
	private String accountId;

	/** Zoho datacenter key (com, eu, in, com.au, jp, ca, sa, com.cn) from the OAuth grant. */
	private String datacenter;

	/**
	 * API host returned with the Zoho grant (api_domain, e.g. https://www.zohoapis.eu). It is
	 * authoritative for where this account's data lives — preferred over deriving a host from
	 * the datacenter key, which cannot know about regions Zoho adds later.
	 */
	private String apiDomain;
}
